apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topics
  namespace: proving-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topic-creator
          image: bitnamilegacy/kafka:4.0.0-debian-12-r10
          command:
            - bash
            - -c
            - |
              kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic shipments --partitions 1 --replication-factor 1 && \
              kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic pcf-results --partitions 1 --replication-factor 1
