
image:
  registry: "ghcr.io/acp-pcvcf"
  repository: "camunda-service"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: camunda-service
  port: 8000
  targetPort: 8000

deployment:
  name: camunda-service
  replicas: 1
  containerPort: 8000

environment:
  zeebe:
    host: "camunda-zeebe-gateway"
    port: 26500
  proofingService:
    host: "proofing-service"
    port: 3000
  sensorService:
    host: "sensor-data-service"
    port: 8080
  verifierService:
    host: "verifier-service.verifier-system.svc.cluster.local"
    port: 80
  pcfRegistryServer:
    host: "pcf-registry-service.proving-system.svc.cluster.local"
    port: 50052
  kafka:
    host: "kafka.proving-system.svc.cluster.local"
    port: 9092
  logLevel: "INFO"
  activitiesOutputPath: "/app/activities.json"
  requestTimeout: "30"

namespace: proving-system
